FROM openjdk
WORKDIR usr/lib
ADD .target/SpringCloudServiceAPI-0.0.1-SNAPSHOT.jar /usr/lib/SpringCloudServiceAPI-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "SpringCloudServiceAPI-0.0.1-SNAPSHOT.jar"]